[package]
name = "intersperse_perf"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "iters"
harness = false
